server:
  port: 9192
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # or create / create-drop
    show-sql: true
  
message: "Hello Department Service"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9194/eureka/
